version: '3.7'

services:
  charge-accounts-service:
    build:
      target: development
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 9229:9229
    depends_on:
      - mongo
      - charge-api-service
    command: npm run start:dev charge-accounts-service
    networks:
      - chargenet
  charge-api-service:
    build:
      target: development
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 9227:9227
    depends_on:
      - charge-relay-service
      - mongo
    command: npm run start:dev charge-api-service
    networks:
      - chargenet
  charge-notifications-service:
    build:
      target: development
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 9230:9230
    depends_on:
      - mongo
      - redis
    command: npm run start:dev charge-notifications-service
    networks:
      - chargenet
  charge-relay-service:
    build:
      target: development
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 9226:9226
    depends_on:
      - mongo
    command: npm run start:dev charge-relay-service
    networks:
      - chargenet
  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami/redis/data
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - chargenet
    restart: always
    volumes:
      - ./data:/data/db
networks:
  chargenet:
