services:
  charge-network-service:
    build:
      target: production
      args:
        SERVICE_NAME: network
        HTTP_PORT: 5004
        TCP_PORT: 8878
    command: npm run start:prod --service=charge-network-service
  charge-accounts-service:
    build:
      target: production
      args:
        SERVICE_NAME: accounts
        HTTP_PORT: 5001
        TCP_PORT: 8875
    command: npm run start:prod --service=charge-accounts-service
  charge-api-service:
    build:
      target: production
      args:
        SERVICE_NAME: api
        HTTP_PORT: 5002
        TCP_PORT: 8876
    command: npm run start:prod --service=charge-api-service
  charge-apps-service:
    build:
      target: production
      args:
        SERVICE_NAME: apps
        HTTP_PORT: 5006
        TCP_PORT: 8880
    command: npm run start:prod --service=charge-apps-service
  charge-smart-wallets-service:
    build:
      target: production
      args:
        SERVICE_NAME: smart-wallets
        HTTP_PORT: 5007
        TCP_PORT: 8881
    command: npm run start:prod --service=charge-smart-wallets-service

  charge-notifications-service:
    build:
      target: production
      args:
        SERVICE_NAME: notifications
        HTTP_PORT: 5005
        TCP_PORT: 8879
    command: npm run start:prod --service=charge-notifications-service
