apiVersion: v1
kind: Secret
metadata:
  name: apps
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mongo_uri: {{ .Values.secrets.mongo_uri | b64enc }}
  charge_public_key: {{ .Values.secrets.charge_public_key | b64enc }}
  charge_secret_key: {{ .Values.secrets.charge_secret_key | b64enc }}
  charge_webhook_id: {{ .Values.secrets.charge_webhook_id | b64enc }}
  unmarshal_auth_key: {{ .Values.secrets.unmarshal_auth_key | b64enc }}
  charge_payments_ethereum_mnemonic: {{ .Values.secrets.charge_payments_ethereum_mnemonic | b64enc }}
  alchemy_webhook_id: {{ .Values.secrets.alchemy_webhook_id | b64enc }}
  alchemy_auth_key: {{ .Values.secrets.alchemy_auth_key | b64enc }}
