apiVersion: v1
kind: Secret
metadata:
  name: api
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mongo_uri: {{ .Values.secrets.mongo_uri | b64enc }}
  rpc_url: {{ .Values.secrets.rpc_url | b64enc  }}
  fuse_studio_admin_jwt: {{ .Values.secrets.fuse_studio_admin_jwt | b64enc  }}
  legacy_jwt_secret: {{ .Values.secrets.legacy_jwt_secret | b64enc  }}
  smart_wallets_jwt_secret: {{ .Values.secrets.smart_wallets_jwt_secret | b64enc }}
  paymaster_production_signer_private_key_v_0_1_0: {{ .Values.secrets.paymaster_production_signer_private_key_v_0_1_0 | b64enc }}
  paymaster_sandbox_signer_private_key_v_0_1_0: {{ .Values.secrets.paymaster_sandbox_signer_private_key_v_0_1_0 | b64enc }}
