apiVersion: v1
kind: Secret
metadata:
  name: notifications
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mongo_uri: {{ .Values.secrets.mongo_uri | b64enc }}
  smart_wallets_jwt_secret: {{ .Values.secrets.smart_wallets_jwt_secret | b64enc }}
  rpc_url: {{ .Values.secrets.rpc_url | b64enc }}
  full_archive_rpc_url: {{ .Values.secrets.full_archive_rpc_url | b64enc }}
