apiVersion: v1
kind: Secret
metadata:
  name: smart-wallets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mongo_uri: {{ .Values.secrets.mongo_uri | b64enc }}
  smart_wallets_jwt_secret: {{ .Values.secrets.smart_wallets_jwt_secret | b64enc }}
  fuse_wallet_backend_jwt: {{ .Values.secrets.fuse_wallet_backend_jwt | b64enc }}
  centrifugo_jwt: {{ .Values.secrets.centrifugo_jwt | b64enc }}
  centrifugo_api_key: {{ .Values.secrets.centrifugo_api_key | b64enc }}
