---
name: Build & Deploy to Kubernetes [QA]

on:
  push:
    branches:
      - qa

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - service_name: accounts
            image: accounts-service
            http_port: 5001
            tcp_port: 8875
          - service_name: api
            image: api-service
            http_port: 5002
            tcp_port: 8876
          - service_name: network
            image: network-service
            http_port: 5004
            tcp_port: 8878
          - service_name: notifications
            image: notifications-service
            http_port: 5005
            tcp_port: 8879
          - service_name: smart-wallets
            image: smart-wallets-service
            http_port: 5007
            tcp_port: 8881
    env:
      PRIVATE_REGISTRY_ENDPOINT: ${{ secrets.PRIVATE_REGISTRY_ENDPOINT }}
      PRIVATE_REGISTRY_REPOSITORY: ${{ secrets.PRIVATE_REGISTRY_REPOSITORY_QA }}
      PRIVATE_REGISTRY_USERNAME: ${{ secrets.PRIVATE_REGISTRY_USERNAME_QA }}
      PRIVATE_REGISTRY_PASSWORD: ${{ secrets.PRIVATE_REGISTRY_PASSWORD_QA }}
    outputs:
      short_sha: ${{ steps.sha.outputs.short_sha }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set GitHub commit short SHA
        id: sha
        run: |
          CALCULATED_SHA=$(git rev-parse --short ${{ github.sha }})
          echo "short_sha=$CALCULATED_SHA" >> $GITHUB_OUTPUT

      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.PRIVATE_REGISTRY_ENDPOINT }}
          username: ${{ env.PRIVATE_REGISTRY_USERNAME }}
          password: ${{ env.PRIVATE_REGISTRY_PASSWORD }}
          logout: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image(s)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.shared
          build-args: |
            SERVICE_NAME=${{ matrix.service_name }}
            HTTP_PORT=${{ matrix.http_port }}
            TCP_PORT=${{ matrix.tcp_port }}
          push: true
          tags: |
            ${{ env.PRIVATE_REGISTRY_ENDPOINT }}/${{ env.PRIVATE_REGISTRY_REPOSITORY }}/${{ matrix.image }}:latest
            ${{ env.PRIVATE_REGISTRY_ENDPOINT }}/${{ env.PRIVATE_REGISTRY_REPOSITORY }}/${{ matrix.image }}:${{ steps.sha.outputs.short_sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      PRIVATE_REGISTRY_ENDPOINT: ${{ secrets.PRIVATE_REGISTRY_ENDPOINT }}
      PRIVATE_REGISTRY_REPOSITORY: ${{ secrets.PRIVATE_REGISTRY_REPOSITORY_QA }}
      K8S_KUBECONFIG: ${{ secrets.K8S_KUBECONFIG_QA }}
      HELM_CHART_REGISTRY_ENDPOINT: ${{ secrets.HELM_CHART_REGISTRY_ENDPOINT }}
      HELM_CHART_REGISTRY_REPOSITORY: ${{ secrets.HELM_CHART_REGISTRY_REPOSITORY }}
      HELM_CHART_REGISTRY_USERNAME: ${{ secrets.HELM_CHART_REGISTRY_USERNAME }}
      HELM_CHART_REGISTRY_PASSWORD: ${{ secrets.HELM_CHART_REGISTRY_PASSWORD }}
      HELM_CHART_VERSION: ${{ vars.HELM_CHART_VERSION_QA }}
      HELM_RELEASE_NAME: ${{ vars.HELM_RELEASE_NAME }}
      HELM_RELEASE_NAMESPACE: ${{ vars.HELM_RELEASE_NAMESPACE }}
    needs: build-and-push
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HELM_CHART_REGISTRY_ENDPOINT }}
          username: ${{ env.HELM_CHART_REGISTRY_USERNAME }}
          password: ${{ env.HELM_CHART_REGISTRY_PASSWORD }}
          logout: true

      - name: Configure Kubernetes config file
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ env.K8S_KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Release
        run: |
          helm upgrade \
            --reset-values \
            --install \
            --history-max 3 \
            --debug \
            --atomic \
            --wait \
            --values helm/values/qa.yaml \
            --set accounts-service.image.repository=${{ env.PRIVATE_REGISTRY_ENDPOINT }}/${{ env.PRIVATE_REGISTRY_REPOSITORY }}/accounts-service \
            --set accounts-service.image.tag=${{ needs.build-and-push.outputs.short_sha }} \
            --set api-service.image.repository=${{ env.PRIVATE_REGISTRY_ENDPOINT }}/${{ env.PRIVATE_REGISTRY_REPOSITORY }}/api-service \
            --set api-service.image.tag=${{ needs.build-and-push.outputs.short_sha }} \
            --set network-service.image.repository=${{ env.PRIVATE_REGISTRY_ENDPOINT }}/${{ env.PRIVATE_REGISTRY_REPOSITORY }}/network-service \
            --set network-service.image.tag=${{ needs.build-and-push.outputs.short_sha }} \
            --set notifications-service.image.repository=${{ env.PRIVATE_REGISTRY_ENDPOINT }}/${{ env.PRIVATE_REGISTRY_REPOSITORY }}/notifications-service \
            --set notifications-service.image.tag=${{ needs.build-and-push.outputs.short_sha }} \
            --set smart-wallets-service.image.repository=${{ env.PRIVATE_REGISTRY_ENDPOINT }}/${{ env.PRIVATE_REGISTRY_REPOSITORY }}/smart-wallets-service \
            --set smart-wallets-service.image.tag=${{ needs.build-and-push.outputs.short_sha }} \
            -n ${{ env.HELM_RELEASE_NAMESPACE }} \
            ${{ env.HELM_RELEASE_NAME }} \
            oci://${{ env.HELM_CHART_REGISTRY_ENDPOINT }}/${{ env.HELM_CHART_REGISTRY_REPOSITORY }} \
            --version ${{ env.HELM_CHART_VERSION }}
